module Main (main) where

import Main.Helpers
import qualified PostgresqlTypes as PostgresqlTypes
import Test.Hspec
import Test.QuickCheck.Instances ()
import qualified TestcontainersPostgresql
import Prelude

main :: IO ()
main =
  hspec do
    withPqConnection TestcontainersPostgresql.Config {forwardLogs = False, auth = TestcontainersPostgresql.TrustAuth, tagName = "postgres:17"} do
      withType @PostgresqlTypes.Bit [mappingSpec]
      withType @PostgresqlTypes.Bool [mappingSpec]
      withType @PostgresqlTypes.Box [mappingSpec]
      withType @PostgresqlTypes.Bytea [mappingSpec]
      withType @PostgresqlTypes.Char [mappingSpec]
      withType @PostgresqlTypes.Cidr [mappingSpec]
      withType @PostgresqlTypes.Circle [mappingSpec]
      withType @PostgresqlTypes.Date [mappingSpec]
      withType @PostgresqlTypes.Float4 [mappingSpec]
      withType @PostgresqlTypes.Float8 [mappingSpec]
      withType @PostgresqlTypes.Inet [mappingSpec]
      withType @PostgresqlTypes.Int2 [mappingSpec]
      withType @PostgresqlTypes.Int4 [mappingSpec]
      withType @PostgresqlTypes.Int8 [mappingSpec]
      withType @PostgresqlTypes.Interval [mappingSpec]
      withType @PostgresqlTypes.IntervalAsMicroseconds [mappingSpec]
      withType @PostgresqlTypes.Json [mappingSpec]
      withType @PostgresqlTypes.Jsonb [mappingSpec]
      withType @PostgresqlTypes.Line [mappingSpec]
      withType @PostgresqlTypes.Lseg [mappingSpec]
      withType @PostgresqlTypes.Macaddr [mappingSpec]
      withType @PostgresqlTypes.Macaddr8 [mappingSpec]
      withType @PostgresqlTypes.Money [mappingSpec]
      withType @PostgresqlTypes.Numeric [mappingSpec]
      withType @PostgresqlTypes.Oid [mappingSpec]
      withType @PostgresqlTypes.Path [mappingSpec]
      withType @PostgresqlTypes.Point [mappingSpec]
      withType @PostgresqlTypes.Polygon [mappingSpec]
      withType @(PostgresqlTypes.Range PostgresqlTypes.Int4) [mappingSpec]
      withType @(PostgresqlTypes.Range PostgresqlTypes.Int8) [mappingSpec]
      withType @(PostgresqlTypes.Range PostgresqlTypes.Numeric) [mappingSpec]
      withType @(PostgresqlTypes.Range PostgresqlTypes.Timestamp) [mappingSpec]
      withType @(PostgresqlTypes.Range PostgresqlTypes.Timestamptz) [mappingSpec]
      withType @(PostgresqlTypes.Range PostgresqlTypes.Date) [mappingSpec]
      withType @(PostgresqlTypes.Multirange PostgresqlTypes.Int4) [mappingSpec]
      withType @(PostgresqlTypes.Multirange PostgresqlTypes.Int8) [mappingSpec]
      withType @(PostgresqlTypes.Multirange PostgresqlTypes.Numeric) [mappingSpec]
      withType @(PostgresqlTypes.Multirange PostgresqlTypes.Timestamp) [mappingSpec]
      withType @(PostgresqlTypes.Multirange PostgresqlTypes.Timestamptz) [mappingSpec]
      withType @(PostgresqlTypes.Multirange PostgresqlTypes.Date) [mappingSpec]
      withType @PostgresqlTypes.Text [mappingSpec]
      withType @PostgresqlTypes.Time [mappingSpec]
      withType @PostgresqlTypes.Timestamp [mappingSpec]
      withType @PostgresqlTypes.Timestamptz [mappingSpec]
      withType @PostgresqlTypes.Timetz [mappingSpec]
      withType @PostgresqlTypes.Uuid [mappingSpec]
      withType @PostgresqlTypes.Varbit [mappingSpec]
      withType @PostgresqlTypes.Varchar [mappingSpec]

    withPqConnection TestcontainersPostgresql.Config {forwardLogs = False, auth = TestcontainersPostgresql.TrustAuth, tagName = "postgres:9"} do
      withType @PostgresqlTypes.Bit [mappingSpec]
      withType @PostgresqlTypes.Bool [mappingSpec]
      withType @PostgresqlTypes.Box [mappingSpec]
      withType @PostgresqlTypes.Bytea [mappingSpec]
      withType @PostgresqlTypes.Char [mappingSpec]
      withType @PostgresqlTypes.Cidr [mappingSpec]
      withType @PostgresqlTypes.Circle [mappingSpec]
      withType @PostgresqlTypes.Date [mappingSpec]
      withType @PostgresqlTypes.Float4 [mappingSpec]
      withType @PostgresqlTypes.Float8 [mappingSpec]
      withType @PostgresqlTypes.Inet [mappingSpec]
      withType @PostgresqlTypes.Int2 [mappingSpec]
      withType @PostgresqlTypes.Int4 [mappingSpec]
      withType @PostgresqlTypes.Int8 [mappingSpec]
      withType @PostgresqlTypes.Interval [mappingSpec]
      withType @PostgresqlTypes.IntervalAsMicroseconds [mappingSpec]
      withType @PostgresqlTypes.Json [mappingSpec]
      withType @PostgresqlTypes.Jsonb [mappingSpec]
      withType @PostgresqlTypes.Line [mappingSpec]
      withType @PostgresqlTypes.Lseg [mappingSpec]
      withType @PostgresqlTypes.Macaddr [mappingSpec]
      withType @PostgresqlTypes.Money [mappingSpec]
      withType @PostgresqlTypes.Numeric [mappingSpec]
      withType @PostgresqlTypes.Oid [mappingSpec]
      withType @PostgresqlTypes.Path [mappingSpec]
      withType @PostgresqlTypes.Point [mappingSpec]
      withType @PostgresqlTypes.Polygon [mappingSpec]
      withType @(PostgresqlTypes.Range PostgresqlTypes.Int4) [mappingSpec]
      withType @(PostgresqlTypes.Range PostgresqlTypes.Int8) [mappingSpec]
      withType @(PostgresqlTypes.Range PostgresqlTypes.Numeric) [mappingSpec]
      withType @(PostgresqlTypes.Range PostgresqlTypes.Timestamp) [mappingSpec]
      withType @(PostgresqlTypes.Range PostgresqlTypes.Timestamptz) [mappingSpec]
      withType @(PostgresqlTypes.Range PostgresqlTypes.Date) [mappingSpec]
      withType @PostgresqlTypes.Text [mappingSpec]
      withType @PostgresqlTypes.Time [mappingSpec]
      withType @PostgresqlTypes.Timestamp [mappingSpec]
      withType @PostgresqlTypes.Timestamptz [mappingSpec]
      withType @PostgresqlTypes.Timetz [mappingSpec]
      withType @PostgresqlTypes.Uuid [mappingSpec]
      withType @PostgresqlTypes.Varbit [mappingSpec]
      withType @PostgresqlTypes.Varchar [mappingSpec]
