module Main (main) where

import Main.Helpers
import qualified PostgresqlTypes.Primitive.Types as PostgresqlTypes.Primitive
import Test.Hspec
import Test.QuickCheck.Instances ()
import qualified TestcontainersPostgresql
import Prelude

main :: IO ()
main =
  hspec do
    withPqConnection TestcontainersPostgresql.Config {forwardLogs = False, auth = TestcontainersPostgresql.TrustAuth, tagName = "postgres:17"} do
      withType @PostgresqlTypes.Primitive.Bit [mappingSpec]
      withType @PostgresqlTypes.Primitive.Bool [mappingSpec]
      withType @PostgresqlTypes.Primitive.Box [mappingSpec]
      withType @PostgresqlTypes.Primitive.Bytea [mappingSpec]
      withType @PostgresqlTypes.Primitive.Char [mappingSpec]
      withType @PostgresqlTypes.Primitive.Cidr [mappingSpec]
      withType @PostgresqlTypes.Primitive.Circle [mappingSpec]
      withType @PostgresqlTypes.Primitive.Date [mappingSpec]
      withType @PostgresqlTypes.Primitive.Float4 [mappingSpec]
      withType @PostgresqlTypes.Primitive.Float8 [mappingSpec]
      withType @PostgresqlTypes.Primitive.Inet [mappingSpec]
      withType @PostgresqlTypes.Primitive.Int2 [mappingSpec]
      withType @PostgresqlTypes.Primitive.Int4 [mappingSpec]
      withType @PostgresqlTypes.Primitive.Int8 [mappingSpec]
      withType @PostgresqlTypes.Primitive.Interval [mappingSpec]
      withType @PostgresqlTypes.Primitive.IntervalAsMicroseconds [mappingSpec]
      withType @PostgresqlTypes.Primitive.Json [mappingSpec]
      withType @PostgresqlTypes.Primitive.Jsonb [mappingSpec]
      withType @PostgresqlTypes.Primitive.Line [mappingSpec]
      withType @PostgresqlTypes.Primitive.Lseg [mappingSpec]
      withType @PostgresqlTypes.Primitive.Macaddr [mappingSpec]
      withType @PostgresqlTypes.Primitive.Macaddr8 [mappingSpec]
      withType @PostgresqlTypes.Primitive.Money [mappingSpec]
      withType @PostgresqlTypes.Primitive.Numeric [mappingSpec]
      withType @PostgresqlTypes.Primitive.Oid [mappingSpec]
      withType @PostgresqlTypes.Primitive.Path [mappingSpec]
      withType @PostgresqlTypes.Primitive.Point [mappingSpec]
      withType @PostgresqlTypes.Primitive.Polygon [mappingSpec]
      withType @(PostgresqlTypes.Primitive.Range PostgresqlTypes.Primitive.Int4) [mappingSpec]
      withType @(PostgresqlTypes.Primitive.Range PostgresqlTypes.Primitive.Int8) [mappingSpec]
      withType @(PostgresqlTypes.Primitive.Range PostgresqlTypes.Primitive.Numeric) [mappingSpec]
      withType @(PostgresqlTypes.Primitive.Range PostgresqlTypes.Primitive.Timestamp) [mappingSpec]
      withType @(PostgresqlTypes.Primitive.Range PostgresqlTypes.Primitive.Timestamptz) [mappingSpec]
      withType @(PostgresqlTypes.Primitive.Range PostgresqlTypes.Primitive.Date) [mappingSpec]
      withType @(PostgresqlTypes.Primitive.Multirange PostgresqlTypes.Primitive.Int4) [mappingSpec]
      withType @(PostgresqlTypes.Primitive.Multirange PostgresqlTypes.Primitive.Int8) [mappingSpec]
      withType @(PostgresqlTypes.Primitive.Multirange PostgresqlTypes.Primitive.Numeric) [mappingSpec]
      withType @(PostgresqlTypes.Primitive.Multirange PostgresqlTypes.Primitive.Timestamp) [mappingSpec]
      withType @(PostgresqlTypes.Primitive.Multirange PostgresqlTypes.Primitive.Timestamptz) [mappingSpec]
      withType @(PostgresqlTypes.Primitive.Multirange PostgresqlTypes.Primitive.Date) [mappingSpec]
      withType @PostgresqlTypes.Primitive.Text [mappingSpec]
      withType @PostgresqlTypes.Primitive.Time [mappingSpec]
      withType @PostgresqlTypes.Primitive.Timestamp [mappingSpec]
      withType @PostgresqlTypes.Primitive.Timestamptz [mappingSpec]
      withType @PostgresqlTypes.Primitive.Timetz [mappingSpec]
      withType @PostgresqlTypes.Primitive.Uuid [mappingSpec]
      withType @PostgresqlTypes.Primitive.Varbit [mappingSpec]
      withType @PostgresqlTypes.Primitive.Varchar [mappingSpec]

    withPqConnection TestcontainersPostgresql.Config {forwardLogs = False, auth = TestcontainersPostgresql.TrustAuth, tagName = "postgres:9"} do
      withType @PostgresqlTypes.Primitive.Bit [mappingSpec]
      withType @PostgresqlTypes.Primitive.Bool [mappingSpec]
      withType @PostgresqlTypes.Primitive.Box [mappingSpec]
      withType @PostgresqlTypes.Primitive.Bytea [mappingSpec]
      withType @PostgresqlTypes.Primitive.Char [mappingSpec]
      withType @PostgresqlTypes.Primitive.Cidr [mappingSpec]
      withType @PostgresqlTypes.Primitive.Circle [mappingSpec]
      withType @PostgresqlTypes.Primitive.Date [mappingSpec]
      withType @PostgresqlTypes.Primitive.Float4 [mappingSpec]
      withType @PostgresqlTypes.Primitive.Float8 [mappingSpec]
      withType @PostgresqlTypes.Primitive.Inet [mappingSpec]
      withType @PostgresqlTypes.Primitive.Int2 [mappingSpec]
      withType @PostgresqlTypes.Primitive.Int4 [mappingSpec]
      withType @PostgresqlTypes.Primitive.Int8 [mappingSpec]
      withType @PostgresqlTypes.Primitive.Interval [mappingSpec]
      withType @PostgresqlTypes.Primitive.IntervalAsMicroseconds [mappingSpec]
      withType @PostgresqlTypes.Primitive.Json [mappingSpec]
      withType @PostgresqlTypes.Primitive.Jsonb [mappingSpec]
      withType @PostgresqlTypes.Primitive.Line [mappingSpec]
      withType @PostgresqlTypes.Primitive.Lseg [mappingSpec]
      withType @PostgresqlTypes.Primitive.Macaddr [mappingSpec]
      withType @PostgresqlTypes.Primitive.Money [mappingSpec]
      withType @PostgresqlTypes.Primitive.Numeric [mappingSpec]
      withType @PostgresqlTypes.Primitive.Oid [mappingSpec]
      withType @PostgresqlTypes.Primitive.Path [mappingSpec]
      withType @PostgresqlTypes.Primitive.Point [mappingSpec]
      withType @PostgresqlTypes.Primitive.Polygon [mappingSpec]
      withType @(PostgresqlTypes.Primitive.Range PostgresqlTypes.Primitive.Int4) [mappingSpec]
      withType @(PostgresqlTypes.Primitive.Range PostgresqlTypes.Primitive.Int8) [mappingSpec]
      withType @(PostgresqlTypes.Primitive.Range PostgresqlTypes.Primitive.Numeric) [mappingSpec]
      withType @(PostgresqlTypes.Primitive.Range PostgresqlTypes.Primitive.Timestamp) [mappingSpec]
      withType @(PostgresqlTypes.Primitive.Range PostgresqlTypes.Primitive.Timestamptz) [mappingSpec]
      withType @(PostgresqlTypes.Primitive.Range PostgresqlTypes.Primitive.Date) [mappingSpec]
      withType @PostgresqlTypes.Primitive.Text [mappingSpec]
      withType @PostgresqlTypes.Primitive.Time [mappingSpec]
      withType @PostgresqlTypes.Primitive.Timestamp [mappingSpec]
      withType @PostgresqlTypes.Primitive.Timestamptz [mappingSpec]
      withType @PostgresqlTypes.Primitive.Timetz [mappingSpec]
      withType @PostgresqlTypes.Primitive.Uuid [mappingSpec]
      withType @PostgresqlTypes.Primitive.Varbit [mappingSpec]
      withType @PostgresqlTypes.Primitive.Varchar [mappingSpec]
